project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks: 
    - notebooks/park-tree-access.qmd

execute:
  freeze: auto
  fig-path: "notebooks/"

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default

editor: visual


